######################################################################
# Automatically generated by qmake (3.0) mer. sept. 27 11:48:33 2017
######################################################################

TEMPLATE = app
TARGET = "test"
INCLUDEPATH += .
INCLUDEPATH += asmx86
QT += widgets
CONFIG += c++14

# Input
SOURCES += main.cpp Window/window.cpp 
HEADERS += Window/window.h
